function recruitmentFigure = batch__export_recruitment_by_pulse(T, response, channel, muscle, pptx, options)
arguments
    T
    response
    channel
    muscle
    pptx = [];
    options.CData (1,3) double = [0 0 0];
    options.MaxPulseIndex (1,1) {mustBeInteger, mustBePositive} = 10;
end

vec = 1:min(max(T.n_pulses),options.MaxPulseIndex);
for iPulse = 1:numel(vec)
    recruitmentFigure = plotRecruitment(T, response, channel, muscle, ...
        'Color', options.CData, ...
        'PulseIndex', vec(iPulse));
    if ~isempty(pptx)
        slideId = pptx.addSlide();
        pptx.addTextbox(num2str(slideId), ...
            'Position',[4 7 0.5 0.5], ...
            'VerticalAlignment','bottom', ...
            'HorizontalAlignment','center', ...
            'FontSize', 10);
        pptx.addTextbox(muscle, ...
            'Position',[0 3.5 10 1.5], ...
            'FontName', 'Tahoma', ...
            'HorizontalAlignment', 'center', ...
            'FontSize', 36);
    end
    for ii = 1:numel(recruitmentFigure)
        if ~isa(recruitmentFigure(ii),'matlab.ui.Figure')
            continue;
        end
        if ~isempty(pptx)
            slideId = pptx.addSlide();
            pptx.addTextbox(num2str(slideId), ...
                'Position',[4 7 0.5 0.5], ...
                'VerticalAlignment','bottom', ...
                'HorizontalAlignment','center', ...
                'FontSize', 10);
            pptx.addTextbox(strrep(recruitmentFigure(ii).UserData.Channel,'\mu','μ'), ...
                'Position',[0 0 10 1], ...
                'FontName', 'Tahoma', ...
                'FontSize', 24);
            pptx.addPicture(recruitmentFigure(ii),'Position',[0 1 10 6.5]);
        end
    end
end
end