%EXAMPLE_LOAD_PLOT_EXPORT_M2_SIMULATIONS  Shows how to load/plot/export the NEURON simulations
clear;
close all force;
clc;

%% 1. Load simulation data for "constant" sweep (all 3 pulses in sets of 3 stimuli have same weight)
% (Assumes you've: 
%   1. Installed NEURON simulator
%   2. From `~/NEURON/MotorNeuron`, in a terminal run `mknrndll`
%   3. From `~/NEURON/MotorNeuron`, in a terminal run `nrniv main.hoc`
%   4. Waited until the NEURON GUI goes away (i.e. it's done simulating)
% )
%
% SEE ALSO: run_neuron_simulation('main_m2_freq_sweep.hoc');
%				|
%				|-> Runs the NEURON simulation sweep from MATLAB!
W1 = 30;
W2 = 30;
W3 = 30;
simdata = load_simulated_data(W1, W2, W3);

%% 2. Plot figures.
fig = plot_simulations(simdata);

%% 3. Create Powerpoint exporter.
% % % Powerpoint Deck exporter % % %
pptx = exportToPPTX('', ...
    'Dimensions',[10, 7.5], ...
    'Title','M2-Modulation MOTONEURON Simulations', ...
    'Author','Max Murphy (MATLAB Auto-gen)', ...
    'Subject','M2-Modulation MOTONEURON Simulations', ...
    'Comments','Uses modulation of gkrect in decades from 0.1x to 10x.');
pptx.addSlide();
pptx.addTextbox('M2-Modulation (NEURON Simulated)', ...
        'Position',[0 3.5 10 1.5], ...
        'FontName', 'Tahoma', ...
        'HorizontalAlignment', 'center', ...
        'FontSize', 36);
slideId = pptx.addSlide();
pptx.addTextbox(sprintf('W1 = %5.2f | W2 = %5.2f | W3 = %5.2f',W1,W2,W3), ...
        'Position',[0 3.5 10 1.5], ...
        'FontName', 'Tahoma', ...
        'HorizontalAlignment', 'center', ...
        'FontSize', 36);
pptx.addTextbox('"Constant" Sweep', ...
    'Position',[0 5 10 1], ...
    'HorizontalAlignment', 'center', ...
    'FontSize', 16);
pptx.addTextbox(num2str(slideId), ...
            'Position',[9.5 7 0.5 0.5], ...
            'VerticalAlignment','bottom', ...
            'HorizontalAlignment','right', ...
            'FontSize', 10);


%% 4. Iterate over figures, saving to Powerpoint.
for iFig = 1:numel(fig)
    slideId = pptx.addSlide();
    pptx.addTextbox(num2str(slideId), ...
            'Position',[9.5 7 0.5 0.5], ...
            'VerticalAlignment','bottom', ...
            'HorizontalAlignment','right', ...
            'FontSize', 10, ...
            'FontName', 'Consolas');
    pptx.addTextbox('Black Solid = membrane voltage at soma', ...
            'Position',[0 6.5 4.5 0.5], ...
            'VerticalAlignment','middle', ...
            'HorizontalAlignment','left', ...
            'FontName', 'Tahoma', ...
            'FontWeight','bold', ...
            'Color', [0 0 0], ...
            'FontSize', 10);
    pptx.addTextbox('Red Dashed = synaptic EPSP onset (stimuli)', ...
            'Position',[0 7.0 4.5 0.5], ...
            'VerticalAlignment','middle', ...
            'HorizontalAlignment','left', ...
            'FontName', 'Tahoma', ...
            'FontWeight', 'bold', ...
            'Color', [1 0 0], ...
            'FontSize', 10);
    pptx.addTextbox('"Constant" Sweep', ...
            'Position',[5.0 6.5 2.5 1.0], ...
            'VerticalAlignment','middle', ...
            'HorizontalAlignment','center', ...
            'FontName', 'Tahoma', ...
            'FontAngle','italic', ...
            'Color', [0.65 0.65 0.65], ...
            'FontSize', 10);
    pptx.addPicture(fig(iFig),'Position',[0.5 0 9 6.5]);
    utils.save_figure(fig(iFig),'export/NEURON/M2-Modulation',sprintf("Recruitment_Vsoma_%ggl_%gm2_Constant",fig(iFig).UserData.Leak, fig(iFig).UserData.M2_Level));
end

%% 5. Load data for "increasing" sweep.
W1 = 10;
W2 = 30;
W3 = 50;
simdata = load_simulated_data(W1, W2, W3);

%% 6. Plot figures.
fig = plot_simulations(simdata);

%% 7. Indicate it's "increasing" sweep.
slideId = pptx.addSlide();
pptx.addTextbox(sprintf('W1 = %5.2f | W2 = %5.2f | W3 = %5.2f',W1,W2,W3), ...
        'Position',[0 3.5 10 1.5], ...
        'FontName', 'Tahoma', ...
        'HorizontalAlignment', 'center', ...
        'FontSize', 36);
pptx.addTextbox('"Increasing" Sweep', ...
    'Position',[0 5 10 1], ...
    'HorizontalAlignment', 'center', ...
    'FontSize', 16);
pptx.addTextbox(num2str(slideId), ...
            'Position',[9.5 7 0.5 0.5], ...
            'VerticalAlignment','bottom', ...
            'HorizontalAlignment','right', ...
            'FontSize', 10);


%% 8. Iterate over figures, saving to Powerpoint.
for iFig = 1:numel(fig)
    slideId = pptx.addSlide();
    pptx.addTextbox(num2str(slideId), ...
            'Position',[9.5 7 0.5 0.5], ...
            'VerticalAlignment','bottom', ...
            'HorizontalAlignment','right', ...
            'FontSize', 10, ...
            'FontName', 'Consolas');
    pptx.addTextbox('Black Solid = membrane voltage at soma', ...
            'Position',[0 6.5 4.5 0.5], ...
            'VerticalAlignment','middle', ...
            'HorizontalAlignment','left', ...
            'FontName', 'Tahoma', ...
            'FontWeight','bold', ...
            'Color', [0 0 0], ...
            'FontSize', 10);
    pptx.addTextbox('Red Dashed = synaptic EPSP onset (stimuli)', ...
            'Position',[0 7.0 4.5 0.5], ...
            'VerticalAlignment','middle', ...
            'HorizontalAlignment','left', ...
            'FontName', 'Tahoma', ...
            'FontWeight', 'bold', ...
            'Color', [1 0 0], ...
            'FontSize', 10);
    pptx.addTextbox('"Increasing" Sweep', ...
            'Position',[5.0 6.5 2.5 1.0], ...
            'VerticalAlignment','middle', ...
            'HorizontalAlignment','center', ...
            'FontName', 'Tahoma', ...
            'FontAngle','italic', ...
            'Color', [0.65 0.65 0.65], ...
            'FontSize', 10);
    pptx.addPicture(fig(iFig),'Position',[0.5 0 9 6.5]);
    utils.save_figure(fig(iFig),'export/NEURON/M2-Modulation',sprintf("Recruitment_Vsoma_%ggl_%gm2_Increasing",fig(iFig).UserData.Leak, fig(iFig).UserData.M2_Level));
end

%% 9. Load data for "up-down" sweep.
W1 = 20;
W2 = 50;
W3 = 20;
simdata = load_simulated_data(W1, W2, W3);

%% 10. Plot figures.
fig = plot_simulations(simdata);

%% 11. Indicate it's "up-down" sweep.
slideId = pptx.addSlide();
pptx.addTextbox(sprintf('W1 = %5.2f | W2 = %5.2f | W3 = %5.2f',W1,W2,W3), ...
        'Position',[0 3.5 10 1.5], ...
        'FontName', 'Tahoma', ...
        'HorizontalAlignment', 'center', ...
        'FontSize', 36);
pptx.addTextbox('"Up-Down" Sweep', ...
    'Position',[0 5 10 1], ...
    'HorizontalAlignment', 'center', ...
    'FontSize', 16);
pptx.addTextbox(num2str(slideId), ...
            'Position',[9.5 7 0.5 0.5], ...
            'VerticalAlignment','bottom', ...
            'HorizontalAlignment','right', ...
            'FontSize', 10);


%% 12. Iterate over figures, saving to Powerpoint.
for iFig = 1:numel(fig)
    slideId = pptx.addSlide();
    pptx.addTextbox(num2str(slideId), ...
            'Position',[9.5 7 0.5 0.5], ...
            'VerticalAlignment','bottom', ...
            'HorizontalAlignment','right', ...
            'FontSize', 10, ...
            'FontName', 'Consolas');
    pptx.addTextbox('Black Solid = membrane voltage at soma', ...
            'Position',[0 6.5 4.5 0.5], ...
            'VerticalAlignment','middle', ...
            'HorizontalAlignment','left', ...
            'FontName', 'Tahoma', ...
            'FontWeight','bold', ...
            'Color', [0 0 0], ...
            'FontSize', 10);
    pptx.addTextbox('Red Dashed = synaptic EPSP onset (stimuli)', ...
            'Position',[0 7.0 4.5 0.5], ...
            'VerticalAlignment','middle', ...
            'HorizontalAlignment','left', ...
            'FontName', 'Tahoma', ...
            'FontWeight', 'bold', ...
            'Color', [1 0 0], ...
            'FontSize', 10);
    pptx.addTextbox('"Up-Down" Sweep', ...
            'Position',[5.0 6.5 2.5 1.0], ...
            'VerticalAlignment','middle', ...
            'HorizontalAlignment','center', ...
            'FontName', 'Tahoma', ...
            'FontAngle','italic', ...
            'Color', [0.65 0.65 0.65], ...
            'FontSize', 10);
    pptx.addPicture(fig(iFig),'Position',[0.5 0 9 6.5]);
    utils.save_figure(fig(iFig),'export/NEURON/M2-Modulation',sprintf("Recruitment_Vsoma_%ggl_%gm2_UpDown",fig(iFig).UserData.Leak, fig(iFig).UserData.M2_Level));
end

%% 13. Load data for "decreasing" sweep.
W1 = 50;
W2 = 30;
W3 = 10;
simdata = load_simulated_data(W1, W2, W3);

%% 14. Plot figures.
fig = plot_simulations(simdata);

%% 15. Indicate it's "decreasing" sweep.
slideId = pptx.addSlide();
pptx.addTextbox(sprintf('W1 = %5.2f | W2 = %5.2f | W3 = %5.2f',W1,W2,W3), ...
        'Position',[0 3.5 10 1.5], ...
        'FontName', 'Tahoma', ...
        'HorizontalAlignment', 'center', ...
        'FontSize', 36);
pptx.addTextbox('"Decreasing" Sweep', ...
    'Position',[0 5 10 1], ...
    'HorizontalAlignment', 'center', ...
    'FontSize', 16);
pptx.addTextbox(num2str(slideId), ...
            'Position',[9.5 7 0.5 0.5], ...
            'VerticalAlignment','bottom', ...
            'HorizontalAlignment','right', ...
            'FontSize', 10);


%% 16. Iterate over figures, saving to Powerpoint.
for iFig = 1:numel(fig)
    slideId = pptx.addSlide();
    pptx.addTextbox(num2str(slideId), ...
            'Position',[9.5 7 0.5 0.5], ...
            'VerticalAlignment','bottom', ...
            'HorizontalAlignment','right', ...
            'FontSize', 10, ...
            'FontName', 'Consolas');
    pptx.addTextbox('Black Solid = membrane voltage at soma', ...
            'Position',[0 6.5 4.5 0.5], ...
            'VerticalAlignment','middle', ...
            'HorizontalAlignment','left', ...
            'FontName', 'Tahoma', ...
            'FontWeight','bold', ...
            'Color', [0 0 0], ...
            'FontSize', 10);
    pptx.addTextbox('Red Dashed = synaptic EPSP onset (stimuli)', ...
            'Position',[0 7.0 4.5 0.5], ...
            'VerticalAlignment','middle', ...
            'HorizontalAlignment','left', ...
            'FontName', 'Tahoma', ...
            'FontWeight', 'bold', ...
            'Color', [1 0 0], ...
            'FontSize', 10);
    pptx.addTextbox('"Decreasing" Sweep', ...
            'Position',[5.0 6.5 2.5 1.0], ...
            'VerticalAlignment','middle', ...
            'HorizontalAlignment','center', ...
            'FontName', 'Tahoma', ...
            'FontAngle','italic', ...
            'Color', [0.65 0.65 0.65], ...
            'FontSize', 10);
    pptx.addPicture(fig(iFig),'Position',[0.5 0 9 6.5]);
    utils.save_figure(fig(iFig),'export/NEURON/M2-Modulation',sprintf("Recruitment_Vsoma_%ggl_%gm2_Decreasing",fig(iFig).UserData.Leak, fig(iFig).UserData.M2_Level));
end

%% 17. Save Powerpoint slide deck for viewing figures.
pptx.save('export/NEURON/M2-Modulation');