function runTestStim(am4100, options)

arguments
    am4100
    options.Intensity (:,1) double = 100;  % Amplitude of biphasic pulses (uA) 
    options.Frequency (:,1) double = 10;    % Within-burst frequency (Hz)
    options.PulseWidth (:,1) double = 200; % Microseconds for minimum pulse width
    options.PostBurstBuffer (1,1) double = 2.5; % (seconds)
    options.BurstDuration (1,1) double = 0.5; % (seconds) width of each burst in time, which determines the total number of pulses based on Frequency (rounding up)
    options.N (1,1) double {mustBePositive, mustBeInteger} = 10;
end

runStimRecSweep([], am4100, [], ...
    'Intensity', options.Intensity, ...
    'Frequency', options.Frequency, ...
    'BurstDuration', options.BurstDuration, ...
    'NBursts', options.N, ...
    'PostBurstBuffer', options.PostBurstBuffer, ...
    'UDP', [], ...
    'StartRecording', false, ...
    'UDPRemotePort', []);

end