function [fig, ax, yEdges, yLab, xEdges, xLab, cdata] = init_somatotopy_fig(options)

arguments
    options.SomatotopyFigureFile = 'Somatotopy-DRGS_Template_Mouse.png';
    options.SomatotopicOutput (1,:) string = ["L-P-DELT", "L-TRI", "L-BIC", "L-WEXT", "L-PARA", "R-PARA", "R-WEXT", "R-BIC", "R-TRI", "R-P-DELT"];
    options.Segments = ["C2", "C3", "C4", "C5", "C6", "C7", "T1", "T2"];
    options.LabelWidth = 148;
    options.LabelYGridExtent = [22, 612];
    options.Width = 1432;
    options.Height = 950;
end

A = imread(options.SomatotopyFigureFile);
r = groot;
if size(r.MonitorPositions,1) > 1
    pos = [r.MonitorPositions(2,1)+20, r.MonitorPositions(2,2)+50, options.Width+40 options.Height];
else
    pos = [20 50 options.Width+40 options.Height];
end
fig = figure(...
    'Name', 'DRGS Somatotopy', ...
    'Color','w',...
    'Units','pixels',...
    'Position', pos);
ax = axes(fig, ...
    'NextPlot','add', ...
    'Units','pixels',...
    'Position',[20, 0, options.Width, options.Height], ...
    'XLim',[0, options.Width-1], ...
    'YLim',[0, options.Height-1], ...
    'Clipping', 'off', ...
    'Color','none',...
    'XColor','none',...
    'YColor','none',...
    'YDir', 'reverse');
image(ax, [0, options.Width-1], [0, options.Height-1], A);
yEdges = round(linspace(options.LabelYGridExtent(1), options.LabelYGridExtent(2), numel(options.Segments)+1));
yLab = options.Segments;
for ii = 1:numel(yEdges)
    h = line(ax, [options.LabelWidth, options.Width], ones(1,2).*yEdges(ii), 'Color', [0 0 0], ...
        'HitTest','off', 'LineStyle', '--', 'LineWidth', 1.5);
    h.Annotation.LegendInformation.IconDisplayStyle = 'off';
end
xEdges = round(linspace(options.LabelWidth, options.Width-2, numel(options.SomatotopicOutput)+1));
xLab = options.SomatotopicOutput;
cdata = cm.map("tartan",'DataType',"double",'N',numel(xLab));
for ii = 2:numel(xEdges)
    h = xline(ax, xEdges(ii), 'Color', [0 0 0], 'LineStyle', ':', 'LineWidth', 1, ...
        'Label', sprintf('\\color[rgb]{%.2f,%.2f,%.2f}%s',cdata(ii-1,:),xLab(ii-1)), ...
        'LabelOrientation', 'aligned', ...
        'LabelVerticalAlignment','bottom','LabelHorizontalAlignment','left', ...
        'FontSize', 64, 'FontName', 'Tahoma', 'FontWeight','bold', ...
        'HitTest','off');
    h.Annotation.LegendInformation.IconDisplayStyle = 'off';
end

end